### ISSUE TITLE
Questions on Kinect Data Reporting and Scale Balanced Grasp Accuracy

### ISSUE THREAD

**Issue by rcao-hk** [mahaoxiang822/Generalizing-Grasp#1]
Hi Haoxiang,

Thank you for your hard work and dedication to this project. I've been following your work with great interest.

I had a couple of questions after reading your paper and checking the repo:

Kinect Data: I noticed there's no data reported on Kinect performance. Is there a reason for this omission? Any plans to include Kinect data in the future?

Scale Balanced Grasp Accuracy: The paper mentions lower accuracy for Scale Balanced Grasp compared to the original. Could you share insights on why this might be?

Appreciate any information you can provide.

Best,

**Comment by mahaoxiang822** [comment]
Hi, thanks for your attention.
**Q1**: Actually, I report the results of kinect data in the supplementary files and soory for the omission. The results  of kinect data is shown below:
| Model                | Seen-AP | Seen-AP0.8 | Seen-AP0.4 | Similar-AP | Similar-AP0.8 | Similar-AP0.4 | Novel-AP | Novel-AP0.8 | Novel-AP0.4 |
|----------------------|---------|------------|------------|------------|---------------|---------------|----------|-------------|-------------|
| GraspNet-baseline    | 27.10   | 30.22      | 24.75      | 25.20      | 27.80         | 24.44         |  6.45    | 7.99        | 3.89        |
| Scale-balanced Grasp | 43.72   | 49.41      | 39.83      | 37.49      | 42.25         | 34.35         | 12.50    | 15.07       | 6.86        |
| GSNet                | 43.97   | 53.28      | 35.53      | 40.07      | 48.58         | 32.03         | 14.54    | 16.50       | 6.96        |
| Ours Baseline        | 57.23   | 65.45      | 49.57      | 48.67      | 55.54         | 43.88         | 18.70    | 23.57       | 8.68        |
| Ours                 | 57.56   | 65.21      | 51.82      | 52.88      | 61.23         | 47.37         | 21.59    | 27.30       | 11.56       |

**Q2**: The training and evaluation protocal is slight different from the original. You can refer to the Sec4.1(implementation details) of our paper.

If you have any other questions,  please feel easy to reply in this issue or contact mahaoxiang822@buaa.edu.cn.

**Comment by rcao-hk** [comment]
Hi, 

Thank you for your reply.

Is it possible to share the fusion point cloud your method feed for real scenes of Graspnet for both cameras?

Best,
Rui

**Comment by mahaoxiang822** [comment]
The code has been updated with fusion point cloud. You can download from google drive link now.
