### ISSUE TITLE
model files and loss function not complete

### ISSUE THREAD

**Issue by lishiyu0088** [mahaoxiang822/Generalizing-Grasp#2]
Dear author,

When I try to download the original graspnet dataset, there are files missing:
FileNotFoundError: [Errno 2] No such file or directory: '/home/LAB/r-yanghongyu/data/graspnet/models/000/grid_sampled_sdf.npz'

When I try to retrain the model I have the following error. Where is FocalLoss_Ori defined?

File "train.py", line 96, in <module>
    from loss import get_loss
  File "Generalizing-Grasp/models/loss.py", line 19, in <module>
    from loss_utils import GRASP_MAX_WIDTH, GRASP_MAX_TOLERANCE, THRESH_GOOD, THRESH_BAD, \
ImportError: cannot import name 'FocalLoss_Ori' from 'loss_utils' (Generalizing-Grasp/utils/loss_utils.py)

Thank you very much.

Best regards

**Comment by mahaoxiang822** [comment]
Sorry for the mistake, 
(1) the definition of FocalLoss_Ori is abandoned now and it has no use in loss.py. I have update the code and comment it. 
(2) for the grid_sampled_sdf.npz, it is actually the SDF file sampled from object models and i forget to upload it. It is quite large and I'm uploading it. I also upload the file for the SDF generation process, you can generate it by yourself by running
```
pip3 install mesh-to-sdf
python dataset/grid_sample.py
```

**Comment by lishiyu0088** [comment]
Thank you very much
