### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by lishiyu0088** [mahaoxiang822/Generalizing-Grasp#4]
Dear author,

I noticed the torch version of this repository is based on torch 1.6, but I install torch 2.1.
so I change
from torch._six import container_abcs
to
import collections.abc as container_abcs
in dataset/mink_dataset.py

But I have cuda out of memory error even if I have batch size 1. I run the code on one 3090 GPU.

Is this error caused by new torch version? If there any solution for this?

**Comment by lishiyu0088** [comment]
I find the model only works with torch 1.8. Version 2.1 will get cuda out of memory error.

**Comment by huamo555** [comment]
> 亲爱的作者，
> 
> 我注意到这个仓库的火炬版本基于 torch 1.6，但我安装了火炬 2.1。所以我从torch._six导入container_abcs更改为导入 collections.abc 作为 dataset/mink_dataset.py 中的container_abcs
> 
> 但是即使我有批量大小 1，我也有 cuda 内存不足错误。我在一个 3090 GPU 上运行代码。
> 
> 此错误是由新的割炬版本引起的吗？如果有什么解决方案吗？

请问您有成功的复现论文指标吗？

**Comment by lishiyu005** [comment]
没有，我的指标比原论文低了10%

**Comment by qingchenkanlu** [comment]
没有问题，我跑出来的结果和论文是接近的
这是复现的结果
Evaluation Result:
realsense, AP Seen=0.6492855509249983
seen
AP 0.6492855509249983
(30, 1, 1, 6)
AP0.4 0.5932388156622598
AP0.8 0.7388208423381585
Mean Accuracy for scene:0148 = 58.159

Evaluation Result:
realsense, AP=0.6437041823496302, AP Similar=0.6437041823496302
similar
AP 0.6437041823496302
(30, 1, 1, 6)
AP0.4 0.6074587496014513
AP0.8 0.7337269966236739
Mean Accuracy for scene:0172 = 30.053

Evaluation Result:
realsense, AP=0.34340065563873906, AP Novel=0.34340065563873906
novel
(30, 1, 1, 6)
AP 0.35524205755731625
AP0.4 0.2144320693278511
AP0.8 0.4120310216090019


这个是作者提供的模型的测试结果
Evaluation Result:
realsense, AP Seen=0.6515814235865608
seen
AP 0.6515814235865608
(30, 1, 1, 6)
AP0.4 0.5906040404101346
AP0.8 0.7443095658493543
Mean Accuracy for scene:0134 = 62.967

Evaluation Result:
realsense, AP=0.644359915960951, AP Similar=0.644359915960951
similar
AP 0.644359915960951
(30, 1, 1, 6)
AP0.4 0.610226924620583
AP0.8 0.7321300151531904
Mean Accuracy for scene:0171 = 26.015

Evaluation Result:
realsense, AP=0.342847648643593, AP Novel=0.342847648643593
novel
(30, 1, 1, 6)
AP 0.3546699813554411
AP0.4 0.21123618684884224
AP0.8 0.41744806849532345

**Comment by huamo555** [comment]
> 没有问题，我跑出来的结果和论文是接近的 这是复现的结果 Evaluation Result: realsense, AP Seen=0.6492855509249983 seen AP 0.6492855509249983 (30, 1, 1, 6) AP0.4 0.5932388156622598 AP0.8 0.7388208423381585 Mean Accuracy for scene:0148 = 58.159
> 
> Evaluation Result: realsense, AP=0.6437041823496302, AP Similar=0.6437041823496302 similar AP 0.6437041823496302 (30, 1, 1, 6) AP0.4 0.6074587496014513 AP0.8 0.7337269966236739 Mean Accuracy for scene:0172 = 30.053
> 
> Evaluation Result: realsense, AP=0.34340065563873906, AP Novel=0.34340065563873906 novel (30, 1, 1, 6) AP 0.35524205755731625 AP0.4 0.2144320693278511 AP0.8 0.4120310216090019
> 
> 这个是作者提供的模型的测试结果 Evaluation Result: realsense, AP Seen=0.6515814235865608 seen AP 0.6515814235865608 (30, 1, 1, 6) AP0.4 0.5906040404101346 AP0.8 0.7443095658493543 Mean Accuracy for scene:0134 = 62.967
> 
> Evaluation Result: realsense, AP=0.644359915960951, AP Similar=0.644359915960951 similar AP 0.644359915960951 (30, 1, 1, 6) AP0.4 0.610226924620583 AP0.8 0.7321300151531904 Mean Accuracy for scene:0171 = 26.015
> 
> Evaluation Result: realsense, AP=0.342847648643593, AP Novel=0.342847648643593 novel (30, 1, 1, 6) AP 0.3546699813554411 AP0.4 0.21123618684884224 AP0.8 0.41744806849532345

请问您修改过论文的参数吗？epoch设置为多少呢？

**Comment by huamo555** [comment]
> 没有，我的指标比原论文低了10%



> 没有，我的指标比原论文低了10%

我复现结果是65.72/62.26/31.14，在seen上接近，但是在similar和novel上都有很大的降低。

**Comment by qingchenkanlu** [comment]
> > 没有问题，我跑出来的结果和论文是接近的 这是复现的结果 Evaluation Result: realsense, AP Seen=0.6492855509249983 seen AP 0.6492855509249983 (30, 1, 1, 6) AP0.4 0.5932388156622598 AP0.8 0.7388208423381585 Mean Accuracy for scene:0148 = 58.159
> > Evaluation Result: realsense, AP=0.6437041823496302, AP Similar=0.6437041823496302 similar AP 0.6437041823496302 (30, 1, 1, 6) AP0.4 0.6074587496014513 AP0.8 0.7337269966236739 Mean Accuracy for scene:0172 = 30.053
> > Evaluation Result: realsense, AP=0.34340065563873906, AP Novel=0.34340065563873906 novel (30, 1, 1, 6) AP 0.35524205755731625 AP0.4 0.2144320693278511 AP0.8 0.4120310216090019
> > 这个是作者提供的模型的测试结果 Evaluation Result: realsense, AP Seen=0.6515814235865608 seen AP 0.6515814235865608 (30, 1, 1, 6) AP0.4 0.5906040404101346 AP0.8 0.7443095658493543 Mean Accuracy for scene:0134 = 62.967
> > Evaluation Result: realsense, AP=0.644359915960951, AP Similar=0.644359915960951 similar AP 0.644359915960951 (30, 1, 1, 6) AP0.4 0.610226924620583 AP0.8 0.7321300151531904 Mean Accuracy for scene:0171 = 26.015
> > Evaluation Result: realsense, AP=0.342847648643593, AP Novel=0.342847648643593 novel (30, 1, 1, 6) AP 0.3546699813554411 AP0.4 0.21123618684884224 AP0.8 0.41744806849532345
> 
> 请问您修改过论文的参数吗？epoch设置为多少呢？

没有做任何其他修改，全都按照原来的论文参数，你可以重新跑一遍或者检查一下数据集处理情况

**Comment by huamo555** [comment]
> > > 没有问题，我跑出来的结果和论文是接近的 这是复现的结果 Evaluation Result: realsense, AP Seen=0.6492855509249983 seen AP 0.6492855509249983 (30, 1, 1, 6) AP0.4 0.5932388156622598 AP0.8 0.7388208423381585 Mean Accuracy for scene:0148 = 58.159
> > > Evaluation Result: realsense, AP=0.6437041823496302, AP Similar=0.6437041823496302 similar AP 0.6437041823496302 (30, 1, 1, 6) AP0.4 0.6074587496014513 AP0.8 0.7337269966236739 Mean Accuracy for scene:0172 = 30.053
> > > Evaluation Result: realsense, AP=0.34340065563873906, AP Novel=0.34340065563873906 novel (30, 1, 1, 6) AP 0.35524205755731625 AP0.4 0.2144320693278511 AP0.8 0.4120310216090019
> > > 这个是作者提供的模型的测试结果 Evaluation Result: realsense, AP Seen=0.6515814235865608 seen AP 0.6515814235865608 (30, 1, 1, 6) AP0.4 0.5906040404101346 AP0.8 0.7443095658493543 Mean Accuracy for scene:0134 = 62.967
> > > Evaluation Result: realsense, AP=0.644359915960951, AP Similar=0.644359915960951 similar AP 0.644359915960951 (30, 1, 1, 6) AP0.4 0.610226924620583 AP0.8 0.7321300151531904 Mean Accuracy for scene:0171 = 26.015
> > > Evaluation Result: realsense, AP=0.342847648643593, AP Novel=0.342847648643593 novel (30, 1, 1, 6) AP 0.3546699813554411 AP0.4 0.21123618684884224 AP0.8 0.41744806849532345
> > 
> > 
> > 请问您修改过论文的参数吗？epoch设置为多少呢？
> 
> 没有做任何其他修改，全都按照原来的论文参数，你可以重新跑一遍或者检查一下数据集处理情况

感谢您的建议，我重新跑了一次实验，得到结果64.07/64.71/34.06，这与论文结果相近。令人困惑的是，我并没有改变任何参数，这与我第一次实验结果相差甚远。

**Comment by Andyyoung0507** [comment]
请问 GraspNet/fusion_scenes/scene_0018/realsense/seg.npy   文件是如何生成的呢？我在训练时遇到了上述文件未找到的报错，但是在readme文件中没有找到相关文件的生成过程，densefusion数据集文件中包含相关的文件但是相关的生成代码我没有找到。 @mahaoxiang822  @qingchenkanlu @lishiyu0088 @huamo555 @huamo555

**Comment by lishiyu005** [comment]
cd scripts
python TSDFreconstruction_dataset.py

**Comment by lishiyu005** [comment]
> 请问 GraspNet/fusion_scenes/scene_0018/realsense/seg.npy 文件是如何生成的呢？我在训练时遇到了上述文件未找到的报错，但是在readme文件中没有找到相关文件的生成过程，densefusion数据集文件中包含相关的文件但是相关的生成代码我没有找到。 @mahaoxiang822 @qingchenkanlu @lishiyu0088 @huamo555 @huamo555

cd scripts
python TSDFreconstruction_dataset.py

**Comment by Andyyoung0507** [comment]
> > 请问 GraspNet/fusion_scenes/scene_0018/realsense/seg.npy 文件是如何生成的呢？我在训练时遇到了上述文件未找到的报错，但是在readme文件中没有找到相关文件的生成过程，densefusion数据集文件中包含相关的文件但是相关的生成代码我没有找到。 @mahaoxiang822 @qingchenkanlu @lishiyu0088 @huamo555 @huamo555
> 
> cd scripts python TSDFreconstruction_dataset.py

 TSDFreconstruction_dataset.py只有points.npy生成吧，我还是没有找到生成seg.npy的相应代码

**Comment by lishiyu005** [comment]
> > > 请问 GraspNet/fusion_scenes/scene_0018/realsense/seg.npy 文件是如何生成的呢？我在训练时遇到了上述文件未找到的报错，但是在readme文件中没有找到相关文件的生成过程，densefusion数据集文件中包含相关的文件但是相关的生成代码我没有找到。 @mahaoxiang822 @qingchenkanlu @lishiyu0088 @huamo555 @huamo555
> > 
> > 
> > cd scripts python TSDFreconstruction_dataset.py
> 
> TSDFreconstruction_dataset.py只有points.npy生成吧，我还是没有找到生成seg.npy的相应代码

https://drive.google.com/file/d/12YODD0ZUu6XTudU1fZBhVtAmIpMZk8xQ/view

**Comment by lishiyu005** [comment]
> > > > 请问 GraspNet/fusion_scenes/scene_0018/realsense/seg.npy 文件是如何生成的呢？我在训练时遇到了上述文件未找到的报错，但是在readme文件中没有找到相关文件的生成过程，densefusion数据集文件中包含相关的文件但是相关的生成代码我没有找到。 @mahaoxiang822 @qingchenkanlu @lishiyu0088 @huamo555 @huamo555
> > > 
> > > 
> > > cd scripts python TSDFreconstruction_dataset.py
> > 
> > 
> > TSDFreconstruction_dataset.py只有points.npy生成吧，我还是没有找到生成seg.npy的相应代码
> 
> https://drive.google.com/file/d/12YODD0ZUu6XTudU1fZBhVtAmIpMZk8xQ/view

确实没有，可以找作者要

**Comment by Andyyoung0507** [comment]
Hello, I encountered a cuda out of memory problem when trying to reproduce the training code. When I adjusted the batch_size to 1, I encountered a dimension information error when processing the loss function. Did you modify the code when reproducing?
@qingchenkanlu @huamo555 @lishiyu005 @lishiyu0088
